spring:
  application:
    name: CrossLAN-Server
logging:
  charset:
    console: utf-8
    file: utf-8
  level:
    root: info
    com.wg.crosslan: debug

crosslan:
  server:
    port: 8088
    bindHost: 0.0.0.0
    token: abcd1234
