// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrossLanMessage.proto

package com.wg.crosslan.common.protocol.proto;

/**
 * Protobuf type {@code CrossLanMessage}
 */
public final class CrossLanMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CrossLanMessage)
    CrossLanMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CrossLanMessage.newBuilder() to construct.
  private CrossLanMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CrossLanMessage() {
    type_ = 0;
    data_ = com.google.protobuf.ByteString.EMPTY;
    channelId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CrossLanMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CrossLanMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readUInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              metaData_ = com.google.protobuf.MapField.newMapField(
                  MetaDataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            metaData__ = input.readMessage(
                MetaDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            metaData_.getMutableMap().put(
                metaData__.getKey(), metaData__.getValue());
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 34: {
            bitField0_ |= 0x00000002;
            data_ = input.readBytes();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000004;
            isSuccess_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            channelId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetMetaData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wg.crosslan.common.protocol.proto.CrossLanMessage.class, com.wg.crosslan.common.protocol.proto.CrossLanMessage.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional uint32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int META_DATA_FIELD_NUMBER = 2;
  private static final class MetaDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_MetaDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metaData_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetaData() {
    if (metaData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaDataDefaultEntryHolder.defaultEntry);
    }
    return metaData_;
  }

  public int getMetaDataCount() {
    return internalGetMetaData().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; meta_data = 2;</code>
   */

  @java.lang.Override
  public boolean containsMetaData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetaData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetaData() {
    return getMetaDataMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta_data = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMetaDataMap() {
    return internalGetMetaData().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta_data = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetaData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; meta_data = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetaData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.Type type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.Type type = 3;</code>
   * @return The type.
   */
  @java.lang.Override public com.wg.crosslan.common.protocol.proto.Type getType() {
    @SuppressWarnings("deprecation")
    com.wg.crosslan.common.protocol.proto.Type result = com.wg.crosslan.common.protocol.proto.Type.valueOf(type_);
    return result == null ? com.wg.crosslan.common.protocol.proto.Type.UNRECOGNIZED : result;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>optional bytes data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int IS_SUCCESS_FIELD_NUMBER = 5;
  private boolean isSuccess_;
  /**
   * <code>optional bool is_success = 5;</code>
   * @return Whether the isSuccess field is set.
   */
  @java.lang.Override
  public boolean hasIsSuccess() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool is_success = 5;</code>
   * @return The isSuccess.
   */
  @java.lang.Override
  public boolean getIsSuccess() {
    return isSuccess_;
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object channelId_;
  /**
   * <code>optional string channel_id = 6;</code>
   * @return Whether the channelId field is set.
   */
  @java.lang.Override
  public boolean hasChannelId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string channel_id = 6;</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string channel_id = 6;</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, id_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetaData(),
        MetaDataDefaultEntryHolder.defaultEntry,
        2);
    if (type_ != com.wg.crosslan.common.protocol.proto.Type.TYPE_NULL.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(4, data_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(5, isSuccess_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, channelId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetaData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metaData__ = MetaDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, metaData__);
    }
    if (type_ != com.wg.crosslan.common.protocol.proto.Type.TYPE_NULL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, data_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isSuccess_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, channelId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wg.crosslan.common.protocol.proto.CrossLanMessage)) {
      return super.equals(obj);
    }
    com.wg.crosslan.common.protocol.proto.CrossLanMessage other = (com.wg.crosslan.common.protocol.proto.CrossLanMessage) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (!internalGetMetaData().equals(
        other.internalGetMetaData())) return false;
    if (type_ != other.type_) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (hasIsSuccess() != other.hasIsSuccess()) return false;
    if (hasIsSuccess()) {
      if (getIsSuccess()
          != other.getIsSuccess()) return false;
    }
    if (hasChannelId() != other.hasChannelId()) return false;
    if (hasChannelId()) {
      if (!getChannelId()
          .equals(other.getChannelId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (!internalGetMetaData().getMap().isEmpty()) {
      hash = (37 * hash) + META_DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetaData().hashCode();
    }
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasIsSuccess()) {
      hash = (37 * hash) + IS_SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSuccess());
    }
    if (hasChannelId()) {
      hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wg.crosslan.common.protocol.proto.CrossLanMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CrossLanMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CrossLanMessage)
      com.wg.crosslan.common.protocol.proto.CrossLanMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMetaData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableMetaData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wg.crosslan.common.protocol.proto.CrossLanMessage.class, com.wg.crosslan.common.protocol.proto.CrossLanMessage.Builder.class);
    }

    // Construct using com.wg.crosslan.common.protocol.proto.CrossLanMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableMetaData().clear();
      type_ = 0;

      data_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      isSuccess_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      channelId_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.internal_static_CrossLanMessage_descriptor;
    }

    @java.lang.Override
    public com.wg.crosslan.common.protocol.proto.CrossLanMessage getDefaultInstanceForType() {
      return com.wg.crosslan.common.protocol.proto.CrossLanMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.wg.crosslan.common.protocol.proto.CrossLanMessage build() {
      com.wg.crosslan.common.protocol.proto.CrossLanMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wg.crosslan.common.protocol.proto.CrossLanMessage buildPartial() {
      com.wg.crosslan.common.protocol.proto.CrossLanMessage result = new com.wg.crosslan.common.protocol.proto.CrossLanMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      result.metaData_ = internalGetMetaData();
      result.metaData_.makeImmutable();
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.data_ = data_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isSuccess_ = isSuccess_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.channelId_ = channelId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wg.crosslan.common.protocol.proto.CrossLanMessage) {
        return mergeFrom((com.wg.crosslan.common.protocol.proto.CrossLanMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wg.crosslan.common.protocol.proto.CrossLanMessage other) {
      if (other == com.wg.crosslan.common.protocol.proto.CrossLanMessage.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      internalGetMutableMetaData().mergeFrom(
          other.internalGetMetaData());
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasData()) {
        setData(other.getData());
      }
      if (other.hasIsSuccess()) {
        setIsSuccess(other.getIsSuccess());
      }
      if (other.hasChannelId()) {
        bitField0_ |= 0x00000010;
        channelId_ = other.channelId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wg.crosslan.common.protocol.proto.CrossLanMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wg.crosslan.common.protocol.proto.CrossLanMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>optional uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metaData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetaData() {
      if (metaData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDataDefaultEntryHolder.defaultEntry);
      }
      return metaData_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMetaData() {
      onChanged();;
      if (metaData_ == null) {
        metaData_ = com.google.protobuf.MapField.newMapField(
            MetaDataDefaultEntryHolder.defaultEntry);
      }
      if (!metaData_.isMutable()) {
        metaData_ = metaData_.copy();
      }
      return metaData_;
    }

    public int getMetaDataCount() {
      return internalGetMetaData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */

    @java.lang.Override
    public boolean containsMetaData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetaData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetaData() {
      return getMetaDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetaDataMap() {
      return internalGetMetaData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMetaData() {
      internalGetMutableMetaData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */

    public Builder removeMetaData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetaData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMetaData() {
      return internalGetMutableMetaData().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */
    public Builder putMetaData(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableMetaData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta_data = 2;</code>
     */

    public Builder putAllMetaData(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetaData().getMutableMap()
          .putAll(values);
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Type type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Type type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.wg.crosslan.common.protocol.proto.Type getType() {
      @SuppressWarnings("deprecation")
      com.wg.crosslan.common.protocol.proto.Type result = com.wg.crosslan.common.protocol.proto.Type.valueOf(type_);
      return result == null ? com.wg.crosslan.common.protocol.proto.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.Type type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.wg.crosslan.common.protocol.proto.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Type type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 4;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private boolean isSuccess_ ;
    /**
     * <code>optional bool is_success = 5;</code>
     * @return Whether the isSuccess field is set.
     */
    @java.lang.Override
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool is_success = 5;</code>
     * @return The isSuccess.
     */
    @java.lang.Override
    public boolean getIsSuccess() {
      return isSuccess_;
    }
    /**
     * <code>optional bool is_success = 5;</code>
     * @param value The isSuccess to set.
     * @return This builder for chaining.
     */
    public Builder setIsSuccess(boolean value) {
      bitField0_ |= 0x00000008;
      isSuccess_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_success = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSuccess() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isSuccess_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <code>optional string channel_id = 6;</code>
     * @return Whether the channelId field is set.
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string channel_id = 6;</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string channel_id = 6;</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string channel_id = 6;</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string channel_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      channelId_ = getDefaultInstance().getChannelId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string channel_id = 6;</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      channelId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CrossLanMessage)
  }

  // @@protoc_insertion_point(class_scope:CrossLanMessage)
  private static final com.wg.crosslan.common.protocol.proto.CrossLanMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wg.crosslan.common.protocol.proto.CrossLanMessage();
  }

  public static com.wg.crosslan.common.protocol.proto.CrossLanMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CrossLanMessage>
      PARSER = new com.google.protobuf.AbstractParser<CrossLanMessage>() {
    @java.lang.Override
    public CrossLanMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CrossLanMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CrossLanMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CrossLanMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wg.crosslan.common.protocol.proto.CrossLanMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

