// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrossLanMessage.proto

package com.wg.crosslan.common.protocol.proto;

public final class CrossLanMessageProto {
  private CrossLanMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrossLanMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrossLanMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrossLanMessage_MetaDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrossLanMessage_MetaDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CrossLanMessage.proto\"\216\002\n\017CrossLanMess" +
      "age\022\017\n\002id\030\001 \001(\rH\000\210\001\001\0221\n\tmeta_data\030\002 \003(\0132" +
      "\036.CrossLanMessage.MetaDataEntry\022\023\n\004type\030" +
      "\003 \001(\0162\005.Type\022\021\n\004data\030\004 \001(\014H\001\210\001\001\022\027\n\nis_su" +
      "ccess\030\005 \001(\010H\002\210\001\001\022\027\n\nchannel_id\030\006 \001(\tH\003\210\001" +
      "\001\032/\n\rMetaDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001B\005\n\003_idB\007\n\005_dataB\r\n\013_is_succes" +
      "sB\r\n\013_channel_id*r\n\004Type\022\r\n\tTYPE_NULL\020\000\022" +
      "\014\n\010REGISTER\020\001\022\023\n\017REGISTER_RESULT\020\002\022\r\n\tCO" +
      "NNECTED\020\003\022\020\n\014DISCONNECTED\020\004\022\010\n\004DATA\020\005\022\r\n" +
      "\tKEEPALIVE\020\006B?\n%com.wg.crosslan.common.p" +
      "rotocol.protoB\024CrossLanMessageProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CrossLanMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrossLanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrossLanMessage_descriptor,
        new java.lang.String[] { "Id", "MetaData", "Type", "Data", "IsSuccess", "ChannelId", "Id", "Data", "IsSuccess", "ChannelId", });
    internal_static_CrossLanMessage_MetaDataEntry_descriptor =
      internal_static_CrossLanMessage_descriptor.getNestedTypes().get(0);
    internal_static_CrossLanMessage_MetaDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrossLanMessage_MetaDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
