// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrossLanMessage.proto

package com.wg.crosslan.common.protocol.proto;

/**
 * Protobuf enum {@code Type}
 */
public enum Type
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TYPE_NULL = 0;</code>
   */
  TYPE_NULL(0),
  /**
   * <code>REGISTER = 1;</code>
   */
  REGISTER(1),
  /**
   * <code>REGISTER_RESULT = 2;</code>
   */
  REGISTER_RESULT(2),
  /**
   * <code>CONNECTED = 3;</code>
   */
  CONNECTED(3),
  /**
   * <code>DISCONNECTED = 4;</code>
   */
  DISCONNECTED(4),
  /**
   * <code>DATA = 5;</code>
   */
  DATA(5),
  /**
   * <code>KEEPALIVE = 6;</code>
   */
  KEEPALIVE(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TYPE_NULL = 0;</code>
   */
  public static final int TYPE_NULL_VALUE = 0;
  /**
   * <code>REGISTER = 1;</code>
   */
  public static final int REGISTER_VALUE = 1;
  /**
   * <code>REGISTER_RESULT = 2;</code>
   */
  public static final int REGISTER_RESULT_VALUE = 2;
  /**
   * <code>CONNECTED = 3;</code>
   */
  public static final int CONNECTED_VALUE = 3;
  /**
   * <code>DISCONNECTED = 4;</code>
   */
  public static final int DISCONNECTED_VALUE = 4;
  /**
   * <code>DATA = 5;</code>
   */
  public static final int DATA_VALUE = 5;
  /**
   * <code>KEEPALIVE = 6;</code>
   */
  public static final int KEEPALIVE_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Type valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Type forNumber(int value) {
    switch (value) {
      case 0: return TYPE_NULL;
      case 1: return REGISTER;
      case 2: return REGISTER_RESULT;
      case 3: return CONNECTED;
      case 4: return DISCONNECTED;
      case 5: return DATA;
      case 6: return KEEPALIVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Type>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Type> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Type>() {
          public Type findValueByNumber(int number) {
            return Type.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.wg.crosslan.common.protocol.proto.CrossLanMessageProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Type[] VALUES = values();

  public static Type valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Type)
}

